---
- name: Deploy docker.sh and symlink to dockerpv
  hosts: all
  gather_facts: no

  vars:
    source_script: docker.sh
    deployed_path: /usr/local/bin/docker.sh
    symlink_path: /usr/local/bin/dockerpv

  pre_tasks:
  - name: Set host-specific credentials for servers
    set_fact:
      ansible_user: "{{ credentials[inventory_hostname].user }}"
      ansible_password: "{{ credentials[inventory_hostname].password }}"
      ansible_become_password: "{{ credentials[inventory_hostname].become_pass }}"
    when: inventory_hostname not in groups['jetsons']

  - name: Set Ansible connection variables
    set_fact:
      ansible_ssh_user: "{{ ansible_user }}"
      ansible_ssh_pass: "{{ ansible_password }}"
      ansible_become_pass: "{{ ansible_become_pass }}"
    when: inventory_hostname in groups['jetsons']

  tasks:
    - name: Copy docker.sh to /usr/local/bin/
      copy:
        src: "{{ source_script }}"
        dest: "{{ deployed_path }}"
        mode: '0755'
      become: yes

    - name: Create symlink dockerpv -> docker.sh
      file:
        src: "{{ deployed_path }}"
        dest: "{{ symlink_path }}"
        state: link
      become: yes