---
- name: Install Docker on all devices
  hosts: server
  vars_files:
    - "{{ inventory_dir }}/group_vars/server_vault.yml"

  pre_tasks:
  - name: Debug credentials
    debug:
      msg: |
        user: {{ ansible_user }}
        become_pass set: {{ ansible_become_password is defined }}
    when: inventory_hostname == "crystal"
  - name: Set host-specific credentials
    set_fact:
      ansible_user: "{{ credentials[inventory_hostname].user }}"
      ansible_password: "{{ credentials[inventory_hostname].password }}"
      ansible_become_password: "{{ credentials[inventory_hostname].become_pass }}"
  - name: Test privilege escalation
    command: whoami
    become: yes
    register: whoami_out

  - debug:
      msg: "Running as: {{ whoami_out.stdout }}"

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      become: yes # After update_cache ensure this is run with sudo otherwise it will fail "permission denied"


    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update APT cache
      apt:
        update_cache: yes
      become: yes # After update_cache ensure this is run with sudo otherwise it will fail "permission denied"

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: ansible_user != 'root'