---
- name: Install CUDA Toolkit
  hosts: all
  gather_facts: no
  become: yes

  pre_tasks:
  - name: Set host-specific credentials for servers
    set_fact:
      ansible_user: "{{ credentials[inventory_hostname].user }}"
      ansible_password: "{{ credentials[inventory_hostname].password }}"
      ansible_become_password: "{{ credentials[inventory_hostname].become_pass }}"
    when: inventory_hostname not in groups['jetsons']
    # when: "'jetsons' not in group_names" works fine too.

  tasks:
    - name: Add NVIDIA package repositories
      shell: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update
      become: true
    - name: Install CUDA
      apt:
        name: cuda-12-6
        state: present
      become: true