---
- name: Install CUDNN
  hosts: all
  gather_facts: no
  become: yes

  pre_tasks:
  - name: Set host-specific credentials for servers
    set_fact:
      ansible_user: "{{ credentials[inventory_hostname].user }}"
      ansible_password: "{{ credentials[inventory_hostname].password }}"
      ansible_become_password: "{{ credentials[inventory_hostname].become_pass }}"
    when: inventory_hostname not in groups['jetsons']
    # when: "'jetsons' not in group_names" works fine too.

  tasks:
    - name: Install CUDNN
      apt:
        name: cudnn
        state: present
      become: true