---
- name: Install CUDNN
  hosts: all
  gather_facts: no
  become: yes

  pre_tasks:
  - name: Set host-specific credentials for servers
    set_fact:
      ansible_user: "{{ credentials[inventory_hostname].user }}"
      ansible_password: "{{ credentials[inventory_hostname].password }}"
      ansible_become_password: "{{ credentials[inventory_hostname].become_pass }}"
    when: inventory_hostname not in groups['jetsons']
    # when: "'jetsons' not in group_names" works fine too.

  tasks:
    - name: Download CUDNN
      shell: |
        wget https://developer.download.nvidia.com/compute/cudnn/9.3.0/local_installers/cudnn-local-repo-ubuntu2204-9.3.0_1.0-1_amd64.deb
        sudo dpkg -i cudnn-local-repo-ubuntu2204-9.3.0_1.0-1_amd64.deb
    - name: Add CUDNN GPG key
      shell: |
        sudo apt-key add /var/cudnn-local-repo-9.3.0/7fa2af80.pub
        sudo cp /var/cudnn-local-repo-ubuntu2204-9.3.0/cudnn-*-keyring.gpg /usr/share/keyrings/
      become: true
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true
    - name: Install CUDNN
      apt:
        name: cudnn
        state: present
      become: true