---
- name: Distribute SSH keys to server hosts
  hosts: all
  gather_facts: no
  become: yes

  pre_tasks:
  - name: Set host-specific credentials for servers
    set_fact:
      ansible_user: "{{ credentials[inventory_hostname].user }}"
      ansible_password: "{{ credentials[inventory_hostname].password }}"
      ansible_become_password: "{{ credentials[inventory_hostname].become_pass }}"
    when: inventory_hostname not in groups['jetsons']
    # when: "'jetsons' not in group_names" works fine too.
      
  - name: Set Ansible connection variables
    set_fact:
      ansible_ssh_user: "{{ ansible_user }}"
      ansible_ssh_pass: "{{ ansible_password }}"

  tasks:
    - name: Copy public key to remote hosts
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/ansible_id_ed25519.pub') }}"
    - name: Copy public key to remote hosts
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"