---
- name: Distribute SSH keys to hosts
  hosts: all
  gather_facts: no
  vars_files:
    - credentials.yml
  become_method: su

  pre_tasks:
    - name: Set host-specific credentials
      set_fact:
        ansible_user: "{{ credentials[inventory_hostname].user }}"
        ansible_password: "{{ credentials[inventory_hostname].password }}"
      no_log: true

    - name: Set Ansible connection variables
      set_fact:
        ansible_ssh_user: "{{ ansible_user }}"
        ansible_ssh_pass: "{{ ansible_password }}"
      no_log: true
  tasks:
    - name: Copy public key to remote hosts
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/ansible_id_ed25519.pub') }}"

